import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import { Tiny5 } from "next/font/google";
import Nav from "@/components/Nav";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const absolution1 = localFont({
  src: "./Absolution-Contextual.woff2",
  variable: "--font-absolution1",
});

const tiny5 = Tiny5({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
  variable: "--font-tiny5",
});

const ft88 = localFont({
  src: "./FT88-Regular.woff",
  variable: "--font-ft88",
});

const GTAmerica = localFont({
  src: [
    { path: "./GT-America-Light.woff", weight: "300" },
    { path: "./GT-America-Regular.woff", weight: "400" },
    { path: "./GT-America-Medium.woff", weight: "500" },
    { path: "./GT-America-Bold.woff", weight: "700" },
    { path: "./GT-America-Black.woff", weight: "900" },
  ],
  variable: "--font-gt-america",
});

const metaOldFrench = localFont({
  src: "./meta-old-french.ttf",
  variable: "--font-meta-old-french",
});

const monumentGrotesk = localFont({
  src: [
    { path: "./MonumentGrotesk-Regular.otf", weight: "400", style: "normal" },
    { path: "./MonumentGrotesk-Italic.otf", weight: "400", style: "italic" },
    { path: "./MonumentGrotesk-Medium.otf", weight: "500", style: "normal" },
    {
      path: "./MonumentGrotesk-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    { path: "./MonumentGrotesk-Bold.otf", weight: "700", style: "normal" },
    {
      path: "./MonumentGrotesk-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
  ],
  variable: "--font-monument-grotesk",
});

const monumentGroteskMono = localFont({
  src: "./MonumentGrotesk-Mono.otf",
  variable: "--font-monument-grotesk-mono",
});

const karlRounded = localFont({
  src: "./KarlST_UltraBlack.woff2",
  variable: "--font-rounded",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${tiny5.variable} ${absolution1.variable} ${ft88.variable} ${GTAmerica.variable} ${metaOldFrench.variable} ${monumentGrotesk.variable} ${monumentGroteskMono.variable} ${karlRounded.variable} antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
