import type { Metadata } from "next";
import localFont from "next/font/local";
import React from "react";
import { Tiny5 } from "next/font/google";
import { Navbar1 } from "@/components/ui/navbar-1";
import Nav from "@/components/Nav";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const absolution1 = localFont({
  src: "./Absolution-Contextual.woff2",
  variable: "--font-absolution1",
});

const tiny5 = Tiny5({
  weight: "400",
  style: "normal",
  display: "swap",
  subsets: ["latin"],
  variable: "--font-tiny5",
});

const ft88 = localFont({
  src: "./FT88-Regular.woff",
  variable: "--font-ft88",
});

const GTAmerica = localFont({
  src: [
    { path: "./GT-America-Light.woff", weight: "300" },
    { path: "./GT-America-Regular.woff", weight: "400" },
    { path: "./GT-America-Medium.woff", weight: "500" },
    { path: "./GT-America-Bold.woff", weight: "700" },
    { path: "./GT-America-Black.woff", weight: "900" },
  ],
  variable: "--font-gt-america",
});

const metaOldFrench = localFont({
  src: "./meta-old-french.ttf",
  variable: "--font-meta-old-french",
});

const nHaasGrotesk = localFont({
  src: [
    { path: "./NHaasGroteskTXPro-55Rg.ttf", weight: "400", style: "normal" },
    { path: "./NHaasGroteskTXPro-65Md.ttf", weight: "500", style: "normal" },
    { path: "./NHaasGroteskTXPro-66MdIt.ttf", weight: "500", style: "italic" },
    { path: "./NHaasGroteskTXPro-75Bd.ttf", weight: "700", style: "normal" },
    { path: "./NHaasGroteskTXPro-76BdIt.ttf", weight: "700", style: "italic" },
  ],
  variable: "--font-nhaas-grotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${tiny5.variable} ${absolution1.variable} ${ft88.variable} ${GTAmerica.variable} ${metaOldFrench.variable} ${nHaasGrotesk.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
